version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: mb_postgres
    restart: always
    environment:
      POSTGRES_USER: mb
      POSTGRES_PASSWORD: mb123
      POSTGRES_DB: mbdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    container_name: mb_server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://mb:mb123@postgres:5432/mbdb?schema=public"
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:
